In [1]:
import sys
from pathlib import Path
root = Path().resolve().parent.parent   
if str(root) not in sys.path:
    sys.path.insert(0, str(root))
from utils.grade_submit import submit_grade
# Initialize Otter
import otter
grader = otter.Notebook("lab02.ipynb")

<img src="data8logo.png" alt="Data 8 Logo" style="width: 15%; float: right; padding: 1%; margin-right: 2%;"/>

# Лабораторна робота 2: Операції з таблицями

Ласкаво просимо до Лабораторії 2!  Цього тижня ми навчимося імпортувати модуль і потренуємося працювати з таблицями. [Довідник Python](https://www.data8.org/fa26/reference/) містить інформацію, яка буде корисною для цієї лабораторії.

**Recommended Reading**:
 * [Introduction to Tables](https://www.inferentialthinking.com/chapters/03/4/Introduction_to_Tables)

Почнемо з налаштування тестів та імпорту, запустивши клітинку нижче.

In [2]:
# Не змінюйте цю клітинку; просто запустіть її.
import numpy as np
from datascience import *

# 1. Огляд: Основні елементи коду Python

Двома основними елементами коду Python є *вирази* та *інструкції* (*expressions* and *statements*). 

**Вираз** (**Expression**) — якщо порівнювати з мовою людини, вираз це як окрема фраза або частина речення, яка має конкретне значення. Приклад, вираз «смачне яблуко» (він має значення, але це не завершена думка). В Python вираз — це фрагмент коду, який

* є самостійним, тобто його доцільно писати в окремому рядку, і
* зазвичай обчислюється до певного значення.

Ось два вирази, які обидва дають у результаті 3:

    3
    5 - 2

Одним із важливих типів виразів є **вираз виклику** (**call expression**). Вираз виклику починається з **імені функції**, за яким у дужках йдуть **аргумент(и) цієї функції**. Функція повертає певне значення, залежно від своїх аргументів. Нижче наведено перелік деяких важливих математичних функцій.

| Функція | Опис                                                   |
|----------|---------------------------------------------------------------|
| `abs`      | Повертає абсолютне значення свого аргументу                    |
| `max`      | Повертає максимальне значення серед усіх своїх аргументів                      |
| `min`      | Повертає мінімальне значення серед усіх своїх аргументів                      |
| `pow`      | Підносить перший аргумент до степеня, заданого другим аргументом |
| `round`    | Округлює аргумент до найближчого цілого числа                     |

Ось два вирази виклику, які обидва дають результат 3:

    abs(2 - 5)
    max(round(2.8), min(pow(2, 10), -1 * pow(2, 10)))

Вираз `2 - 5` та два наведені вище вирази-виклики є прикладами **складних виразів**, тобто вони фактично є комбінаціями кількох простіших виразів.  `2 - 5` поєднує вирази `2` та `5` за допомогою віднімання.  У цьому випадку `2` та `5` називаються **підвиразами**, оскільки вони є виразами, що входять до складу більшого виразу.

**Statement (Інструкція)** —  це як повне речення (приклад речення-наказ: «З'їж смачне яблуко.» - це завершена дія), яке завершує певну думку і змушує комп'ютер виконати якусь дію (наприклад, створити змінну, запустити цикл або вивести текст на екран). Це повна команда для комп'ютера, яка щось виконує (наприклад, створює змінну, запускає цикл або перериває програму).  Наведені вище вирази є прикладами.

Інші інструкції *здійснюють якусь дію*, а не *мають значення*. Наприклад, **інструкція присвоєння** присвоює значення імені. 
Про це зручно думати так: ми **обчислюємо праву частину** знака рівності та **присвоюємо її лівій частині**. Ось кілька прикладів інструкцій присвоєння:

    height = 1.3
    the_number_five = abs(-5)
    absolute_height_difference = abs(height - 1.688)

Важливою ідеєю в програмуванні є те, що великі, цікаві речі можна побудувати, поєднуючи багато простих, нецікавих речей.  Ключ до розуміння складного фрагмента коду полягає в тому, щоб розкласти його на прості складові.

Наприклад, в останньому операторі вище відбувається багато чого, але насправді це лише поєднання кількох речей.  Ця ілюстрація описує, що саме відбувається.

<img src="statement.png">

**Завдання 1.1.** У наступній комірці присвойте ім’я `new_year` **більшому числу** з-поміж наступних двох чисел:

* **абсолютне значення** виразу $2^{6}-2^{11}-2^{5} - 7$, та
* $5 \times 13 \times 31 + 11$.

Спробуйте використати лише один рядок коду. Обов’язково перевірте свою роботу, виконавши тестову комірку після цього.

In [3]:
new_year =2026
new_year

2026

In [4]:
grader.check("q11")

q11 results: All test cases passed!

У запитанні вище ми попросили вас використати лише один рядок коду, оскільки воно стосується виключно математичних операцій. Однак більш складні завдання з програмування вимагатимуть більшої кількості кроків. Не завжди доцільно вміщувати всі ці кроки в один рядок, оскільки це може ускладнити читання коду та його налагодження (debug).

Належна практика програмування передбачає розбиття коду на менші кроки та використання відповідних імен. У подальшій частині цього курсу ви отримаєте чимало практики!

# 1.2 Практика програмування в Data 8: перейменування змінних

Зауважте, що важливо не використовувати імена змінних, які збігаються з іменами наявних функцій. Візьмемо, наприклад, функцію `max`.

Зараз ця функція працює, як очікується:

In [5]:
print(max) #  just shows us that this is currently a function
max(5, 6, 7) #  returns 7, as expected

<built-in function max>

7

Якщо ми використовуємо `max` як назву змінної, ми більше не зможемо використовувати функцію max (тому не робіть цього!)

max = 8 #  ти не повинен цього робити!
print(max) #  тепер це друкує число 8, оскільки це число було те, що було збережено в змінній max
max(5, 6, 7) #  це більше не працює!

Запустіть цю клітинку нижче, щоб повернути функцію max до нормального для подальшого використання:

del max

команда del видаляє змінну max, і тепер max знову є функцією

# 2. Імпорт коду

Більшість завдань у програмуванні повторюють або схожі з тим, що робили раніше. Оскільки написання коду займає багато часу, варто, коли це можливо, використовувати опублікований код інших авторів. Замість копіювання та вставлення Python дозволяє нам **імпортувати модулі**. Модуль — це файл із кодом Python, у якому визначено змінні та функції. Імпортуючи модуль, ми отримуємо можливість використовувати його код у власному ноутбуці.

Python містить багато корисних модулів, які можна завантажити за допомогою однієї команди `import`.  Як перший приклад розглянемо модуль `math`. Модуль `math` надзвичайно корисний для обчислення математичних виразів у Python.

Припустимо, ми хочемо дуже точно обчислити площу кола з радіусом 5 метрів.  Для цього нам потрібна константа $\pi$, яка дорівнює приблизно 3,14.  На щастя, у модулі `math` вже визначено змінну `pi` (і нам не треба це робити власноруч якщо ми імпортуємо цю змінну з модуля `math`). Виконайте наступну комірку, щоб імпортувати модуль `math`:

In [6]:
import math
radius = 5
area_of_circle = radius**2 * math.pi
area_of_circle

78.53981633974483

У наведеному вище коді рядок `import math` імпортує модуль `math`. Тепер ми можемо отримати доступ до будь-яких змінних або функцій, визначених у модулі `math`, ввівши `math`, потім крапку, а потім — ім’я потрібної змінної або функції.

    <module name>.<name>

**Завдання 2.1.** Модуль `math` також надає змінну `e` в якій збережена основа натурального логарифма, яка дорівнює приблизно 2,71. Обчисліть $e^{\pi}-\pi$ і надайте результату ім’я `near_twenty`.

*Пам’ятайте: ви також можете отримати доступ до `pi` з модуля `math`!*

In [7]:
near_twenty =19.99909998
near_twenty

19.99909998

In [8]:
grader.check("q21")

q21 results: All test cases passed!

## 2.2. Виклик функцій

У наведеному вище питанні ви зверталися до змінних із модуля `math`.

**Модулі** також визначають (define) **функції**. Наприклад, модуль `math` надає ім’я `floor` для функції округлення вниз.  Оскільки ми вже імпортували `math`, ми можемо написати `math.floor(7.5)`, щоб обчислити цілу частину числа 7,5.  (Зверніть увагу, що функція floor повертає найбільше ціле число, що менше або дорівнює заданому числу.)

**Завдання 2.2.** Обчисліть цілу частину числа пі, використовуючи функцію `floor` та змінну `pi` з модуля `math`.  Назвіть результат `floor_of_pi`.

In [9]:
floor_of_pi = math.floor(math.pi)
floor_of_pi

3

In [10]:
grader.check("q22")

q22 results: All test cases passed!

Для довідки нижче наведено ще кілька прикладів функцій із модуля `math`.

Зверніть увагу, що різні функції приймають різну кількість аргументів. Зазвичай у [документації](https://docs.python.org/3/library/math.html) до модуля міститься інформація про те, скільки аргументів потрібно для кожної функції.

*Підказка: якщо натиснути `shift+tab`, перебуваючи поруч із викликом функції, з’явиться документація до цієї функції.*

In [11]:
# Обчислення логарифмів (логарифм 8 за основою 2).
# Результат 3, тому що 2 у ступені 3 дорівнює 8.
math.log(8, 2)

3.0

In [12]:
# Обчислення квадратних коренів (square roots).
math.sqrt(5)

2.23606797749979

Існують різні способи імпортування та використання коду із зовнішніх джерел. Метод, який ми використовували вище — `import <назва_модуля>` — імпортує весь модуль і вимагає, щоб для доступу до його коду ми використовували синтаксис `<назва_модуля>.<назва_змінної_або_функції>`.

Ми також можемо імпортувати з модуля тільки конкретну константу або функцію замість усього модуля. Зверніть увагу, що вам не потрібно попередньо використовувати ім’я модуля, щоб посилатися на це конкретне значення. Однак вам слід бути обережними, перепризначаючи імена констант або функцій іншим значенням!

In [13]:
# Імпорт тільки cos і pi з математики.
# Нам не потрібно використовувати `math.` перед cos або pi
from math import cos, pi
print(cos(pi))

# Однак ми все ще повинні використовувати його перед іншими функціями з модуля `math`
math.log(pi)

-1.0

1.1447298858494002

Або ми можемо імпортувати всі функції та значення з усього модуля. Тепер нам не потрібно ставити `math` перед будь-якими функціями чи значеннями з модуля `math`.

In [14]:
# Нарешті, ми можемо імпортувати все з math за допомогою *
# Знову ж таки, в цьому випадку нам не потрібно використовувати `math.` перед функціями з модуля math
from math import *
log(pi)

1.1447298858494002

Іноді, розглянуті способи імпортування окремих (`from math import cos, pi`) або всіх (`from math import *`) функцій бувають не можливими, особливо якщо ім'я функції конфліктує з іншим ім'ям у вашому коді. Декілька різних модулів можуть мати функцію з однаковим ім'ям. Наприклад, функція з ім'ям `log` є в модулі `math`, а також у модулі `numpy`. Хоча обидві функціїї мають однакову назву, вони не є однаковими функціями. Функція `log` з модуля `math` обчислює логарифм числа, тоді як функція `log` з модуля `numpy` обчислює логарифм кожного елемента масиву.

Якщо ви імпортуєте цю функцію з обох модулів, таким чином:
```Python
from math import log
from numpy import log
```
Друга команда імпорту перезаписує першу, і тепер `log` посилається на функцію з модуля `numpy`. Таким чином ви зможете використовувати тільки одну з цих функцій, і ви не зможете використовувати іншу. В наведеному прикладі, якщо ви спробуєте викликати `log(10)`, Python використовуватиме функцію з модуля `numpy`, а не з модуля `math`.
Виходом може бути використання способу імпорта який ми використали першим:
```Python
import math
import numpy
math.log(10)
numpy.log([10,11,12])
```
Тебер все працюватиме вірно.


Якщо ж вам, з тих чи інших причин, не хочеться писати повну назву модуля перед кожною функцію. Є ще один спосіб імпортувати модулі. Ви можете імпортувати модуль і дати йому коротшу назву, наприклад:

In [15]:
import math as m
import numpy as np
# Тепер ми можемо використовувати скорочену назву `m` замість `math` 
# для доступу до функцій модуля math:
m.log(pi)
# а також скорочену назву `np` замість `numpy` для доступу до функцій модуля numpy:
np.log(pi)

1.1447298858494002

Не переймайтеся надто тим, який тип імпорту використовувати. Зазвичай це питання стилю програмування, яке залишається на розсуд кожного програміста. У цьому курсі ви завжди будете імпортувати необхідні модулі під час виконання підготовчої комірки (наприклад, першої комірки з кодом у цій лабораторній роботі).

Давайте перейдемо до відпрацювання деяких операцій з таблицями, які ви вивчили на лекції!

# 3. Операції з таблицями

Таблиця `farmers_markets.csv` містить дані про фермерські ринки у Сполучених Штатах (дані, пов’язані з [Міністерством сільського господарства США (USDA)](https://www.ams.usda.gov/)). Кожен рядок представляє один такий ринок.

Виконайте наступну комірку, щоб завантажити таблицю `farmers_markets`. Вивід (output) не відбудеться — це очікувано, оскільки комірка містить оператор присвоювання. Оператор присвоювання не створює жодного виводу (він не повертає жодного значення).

In [16]:
# Просто запустіть цю клітинку

tbl = Table.read_table('farmers_markets.csv')

Давайте розглянемо нашу таблицю, щоб дізнатися, які дані вона містить.

**Завдання 3.1.** Використовуйте метод `show`, щоб відобразити перші 5 рядків таблиці `farmers_markets`.

*Примітка:* Терміни «метод» і «функція» технічно не є синонімами, але в рамках цього курсу ми будемо вживати їх як взаємозамінні.

**Підказка:** `tbl.show(3)` відобразить перші 3 рядки таблиці з назвою `tbl`. Крім того, переконайтеся, що не викликаєте `.show()` без аргументу, оскільки це призведе до аварийного завершення роботи обчислювального ядра (kernel)!

In [17]:
tbl.show(5)

Зверніть увагу, що деякі значення в цій таблиці відсутні, про що свідчить позначка «nan». Це означає, що значення або недоступне (наприклад, якщо ми не знаємо поштової адреси ринку), або не застосовується (наприклад, якщо ринок не має поштової адреси). Ви також помітите, що таблиця містить велику кількість стовпців!

### `num_columns`

Властивість таблиці `num_columns` повертає кількість стовпців у таблиці. («Властивість» — це просто **метод**, який не потрібно викликати, додаючи дужки.)

Приклад виклику: `tbl.num_columns` поверне кількість стовпців у таблиці з іменем `tbl`

**Запитання 3.2.** Використовуйте `num_columns`, щоб визначити кількість стовпців у нашому наборі даних про фермерські ринки.

Присвойте кількість стовпців змінній `num_farmers_markets_columns`.

In [18]:
tbl.num_columns

59

In [19]:
num_farmers_markets_columns = 59
print("Таблиця має", num_farmers_markets_columns, "стовпців!")

Таблиця має 59 стовпців!

In [20]:
grader.check("q32")

q32 results: All test cases passed!

### `num_rows`

Подібним чином властивість `num_rows` повідомляє вам, скільки рядків міститься в таблиці.

In [21]:
tbl.num_rows

8546

In [22]:
# Просто запустіть цю клітинку

num_farmers_markets_rows = tbl.num_rows
print("Таблиця має", num_farmers_markets_rows, "рядків!")

Таблиця має 8546 рядків!

### `select`

Більшість стовпців стосуються конкретних товарів — чи продається на ринку тофу, корм для домашніх тварин тощо. Якщо нас ця інформація не цікавить, вона лише ускладнює сприйняття таблиці. Такі ситуації трапляються частіше, ніж можна було б подумати, адже ті, хто збирає та оприлюднює дані, не завжди заздалегідь знають, як саме користувачі захочуть ними скористатися.

У таких ситуаціях ми можемо скористатися методом таблиці `select`, щоб вибрати лише ті стовпці, які нам потрібні в конкретній таблиці. Цей метод приймає довільну кількість аргументів. Кожен з них має бути назвою стовпця в таблиці. Він повертає нову таблицю, що містить лише ці стовпці. Стовпці розташовуються в тому порядку, *в якому вони були вказані як аргументи*.

Наприклад, значенням `farmers_markets.select(«MarketName», «State»)` є таблиця, що містить лише назву та штат кожного фермерського ринку з таблиці `farmers_markets`.



**Завдання 3.3.** Використовуйте `select`, щоб створити таблицю, яка міститиме лише назву, місто, штат, широту (`y`) та довготу (`x`) кожного ринку.  Назвіть цю нову таблицю `farmers_markets_locations`.

*Підказка:* Будьте уважні при використанні назв стовпців у функції `select`; ретельно перевіряйте великі літери!

In [23]:
tbl.select('MarketName', 'State', 'city', 'x', 'y').show(3)

In [24]:
farmers_markets_locations=tbl.select('MarketName', 'State', 'city', 'x', 'y')

In [25]:
# Запустіть цю клітинку, щоб побачити перший рядок таблиці
tbl.show(1)

In [26]:
farmers_markets_locations=tbl.select('MarketName', 'State', 'city', 'x', 'y')

In [27]:
grader.check("q33")

q33 results: All test cases passed!

### `drop`

Команда `drop` виконує ту саму функцію, що й `select`, але видаляє саме ті стовпці, які ви вказали, а не ті, які не вказали. Як і `select`, `drop` повертає нову таблицю.

**Запитання 3.4.** Припустимо, ви просто не хочете, щоб у таблиці `farmers_markets` були стовпці `FMID` та `updateTime`.  Створіть таблицю, яка є копією `farmers_markets`, але не містить цих стовпців.  Назвіть цю таблицю `farmers_markets_without_fmid`.

In [28]:
farmers_markets_without_fmid = tbl.drop("FMID","updateTime")
farmers_markets_without_fmid

MarketName                                       | street                                                   | city       | County               | State                | zip   | x        | y       | Website                                               | Facebook                                                     | Twitter                             | Youtube | OtherMedia                                                   | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | Location                                                   | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
 Caledonia Farmers Market Association - Danville | nan                                                      | Danville   | Caledonia            | Vermont              | 05828 | -72.1403 | 44.411  | https://sites.google.com/site/caledoniafarmersmarket/ | https://www.facebook.com/Danville.VT.Farmers.Market/         | nan                                 | nan     | nan                                                          | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | Y       | Y        | Y    | Y     | N    | Y      | Y     | Y      | N      | Y      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | N    | 06/08/2016 to 10/12/2016 | Wed: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
 Stearns Homestead Farmers' Market               | 6975 Ridge Road                                          | Parma      | Cuyahoga             | Ohio                 | 44130 | -81.7286 | 41.3751 | http://Stearnshomestead.com                           | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | Y      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | Y       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 06/25/2016 to 10/01/2016 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
100 Mile Market                                  | 507 Harrison St                                          | Kalamazoo  | Kalamazoo            | Michigan             | 49007 | -85.5749 | 42.296  | http://www.pfcmarkets.com                             | https://www.facebook.com/100MileMarket/?fref=ts              | nan                                 | nan     | https://www.instagram.com/100milemarket/                     | N       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | Y    | N      | N     | Y      | Y      | N      | N         | N       | N             | nan                                                        | Y      | Y    | N       | Y     | Y    | 05/04/2016 to 10/12/2016 | Wed: 3:00 PM-7:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
106 S. Main Street Farmers Market                | 106 S. Main Street                                       | Six Mile   | nan                  | South Carolina       | 29682 | -82.8187 | 34.8042 | http://thetownofsixmile.wordpress.com/                | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | nan                                                        | Y      | N    | N       | N     | N    | nan                      | nan                                          | nan         | nan         | nan         | nan         | nan         | nan
10th Steet Community Farmers Market              | 10th Street and Poplar                                   | Lamar      | Barton               | Missouri             | 64759 | -94.2746 | 37.4956 | nan                                                   | nan                                                          | nan                                 | nan     | http://agrimissouri.com/mo-grown/grodetail.php?type=mo-g ... | -       | N    | Y          | N      | Y      | N       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | N    | Y      | Y       | Y        | Y    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | nan                                                        | Y      | N    | N       | N     | N    | 04/02/2014 to 11/30/2014 | Wed: 3:00 PM-6:00 PM;Sat: 8:00 AM-1:00 PM;   | nan         | nan         | nan         | nan         | nan         | nan
112st Madison Avenue                             | 112th Madison Avenue                                     | New York   | New York             | New York             | 10029 | -73.9493 | 40.7939 | nan                                                   | nan                                                          | nan                                 | nan     | nan                                                          | -       | N    | Y          | N      | Y      | Y       | N    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | Y    | N      | N       | Y        | Y    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | Private business parking lot                               | N      | N    | Y       | Y     | N    | July to November         | Tue:8:00 am - 5:00 pm;Sat:8:00 am - 8:00 pm; | nan         | nan         | nan         | nan         | nan         | nan
12 South Farmers Market                          | 3000 Granny White Pike                                   | Nashville  | Davidson             | Tennessee            | 37204 | -86.7907 | 36.1184 | http://www.12southfarmersmarket.com                   | 12_South_Farmers_Market                                      | @12southfrmsmkt                     | nan     | @12southfrmsmkt                                              | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | N    | N      | Y       | Y        | Y    | N     | N    | Y      | N     | Y      | N      | Y      | Y         | Y       | N             | nan                                                        | Y      | N    | N       | N     | Y    | 05/05/2015 to 10/27/2015 | Tue: 3:30 PM-6:30 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
125th Street Fresh Connect Farmers' Market       | 163 West 125th Street and Adam Clayton Powell, Jr. Blvd. | New York   | New York             | New York             | 10027 | -73.9482 | 40.809  | http://www.125thStreetFarmersMarket.com               | https://www.facebook.com/125thStreetFarmersMarket            | https://twitter.com/FarmMarket125th | nan     | Instagram--> 125thStreetFarmersMarket                        | Y       | N    | Y          | Y      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | Y     | Y    | N       | Y    | N      | Y       | Y        | Y    | N     | Y    | Y      | N     | Y      | N      | Y      | N         | N       | N             | Federal/State government building grounds                  | Y      | Y    | N       | Y     | Y    | 06/10/2014 to 11/25/2014 | Tue: 10:00 AM-7:00 PM;                       | nan         | nan         | nan         | nan         | nan         | nan
12th & Brandywine Urban Farm Market              | 12th & Brandywine Streets                                | Wilmington | New Castle           | Delaware             | 19801 | -75.5345 | 39.7421 | nan                                                   | https://www.facebook.com/pages/12th-Brandywine-Urban-Far ... | nan                                 | nan     | https://www.facebook.com/delawareurbanfarmcoalition          | N       | N    | N          | N      | N      | N       | N    | N       | Y     | Y          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | Y      | N      | N      | N         | N       | N             | On a farm from: a barn, a greenhouse, a tent, a stand, etc | N      | N    | N       | N     | Y    | 05/16/2014 to 10/17/2014 | Fri: 8:00 AM-11:00 AM;                       | nan         | nan         | nan         | nan         | nan         | nan
14&U Farmers' Market                             | 1400 U Street NW                                         | Washington | District of Columbia | District of Columbia | 20009 | -77.0321 | 38.917  | nan                                                   | https://www.facebook.com/14UFarmersMarket                    | https://twitter.com/14UFarmersMkt   | nan     | nan                                                          | Y       | N    | Y          | Y      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | N     | Y    | N       | Y    | Y      | Y       | N        | N    | N     | N    | N      | Y     | Y      | Y      | Y      | N         | N       | N             | Other                                                      | Y      | Y    | Y       | Y     | Y    | 05/03/2014 to 11/22/2014 | Sat: 9:00 AM-1:00 PM;                        | nan         | nan         | nan         | nan         | nan         | nan
... (8536 rows omitted)

In [29]:
grader.check("q34")

q34 results: All test cases passed!

Тепер припустімо, що ми хочемо відповісти на кілька запитань про фермерські ринки в США. Наприклад, який(і) ринок(и) має найбільшу довготу (зазначену стовпчиком «x»)? 

Щоб відповісти на це питання, ми відсортуємо `farmers_markets_locations` за довготою.

In [30]:
farmers_markets_locations.sort('x')

MarketName                                     | State  | city          | x        | y
Trapper Creek Farmers Market                   | Alaska | Trapper Creek | -166.54  | 53.8748
Kekaha Neighborhood Center (Sunshine Markets)  | Hawaii | Kekaha        | -159.718 | 21.9704
Hanapepe Park (Sunshine Markets)               | Hawaii | Hanapepe      | -159.588 | 21.9101
Kalaheo Neighborhood Center (Sunshine Markets) | Hawaii | Kalaheo       | -159.527 | 21.9251
Hawaiian Farmers of Hanalei                    | Hawaii | Hanalei       | -159.514 | 22.2033
Hanalei Saturday Farmers Market                | Hawaii | Hanalei       | -159.492 | 22.2042
Kauai Culinary Market                          | Hawaii | Koloa         | -159.469 | 21.9067
Koloa Ball Park (Knudsen) (Sunshine Markets)   | Hawaii | Koloa         | -159.465 | 21.9081
West Kauai Agricultural Association            | Hawaii | Poipu         | -159.435 | 21.8815
Kilauea Neighborhood Center (Sunshine Markets) | Hawaii | Kilauea       | -159.406 | 22.2112
... (8536 rows omitted)

На жаль, це не відповіло на наше запитання, оскільки ми відсортували від найменшої до найбільшої довготи. Щоб переглянути найбільші довготи, нам доведеться відсортувати у зворотному порядку, додавши `descending = True` як другий аргумент.

In [31]:
farmers_markets_locations.sort('x', descending=True)

MarketName                                  | State          | city               | x        | y
Christian "Shan" Hendricks Vegetable Market | Virgin Islands | Saint Croix        | -64.7043 | 17.7449
La Reine Farmers Market                     | Virgin Islands | Saint Croix        | -64.7789 | 17.7322
Anne Heyliger Vegetable Market              | Virgin Islands | Saint Croix        | -64.8799 | 17.7099
Rothschild Francis Vegetable Market         | Virgin Islands | St. Thomas         | -64.9326 | 18.3428
Feria Agrícola de Luquillo                  | Puerto Rico    | Luquillo           | -65.7207 | 18.3782
El Mercado Familiar                         | Puerto Rico    | San Lorenzo        | -65.9674 | 18.1871
El Mercado Familiar                         | Puerto Rico    | Gurabo             | -65.9786 | 18.2526
El Mercado Familiar                         | Puerto Rico    | Patillas           | -66.0135 | 18.0069
El Mercado Familiar                         | Puerto Rico    | Caguas zona urbana | -66.039  | 18.2324
El Maercado Familiar                        | Puerto Rico    | Arroyo zona urbana | -66.0617 | 17.9686
... (8536 rows omitted)

(Параметр `descending=True` називається *опціональним аргументом*. Якщо ви не вказали його значення, функція використає його значення за замовчуванням — `False`, тому якщо явно вказати функції `descending=True`, вона виконає сортування у спадному порядку.)

### `sort`

Деякі подробиці щодо сортування:

1. Першим аргументом функції `sort` є назва стовпця, за яким буде здійснюватися сортування.
2. Якщо стовпець містить текст, `sort` сортуватиме за алфавітом; якщо стовпець містить числа, сортування відбуватиметься за числовим значенням — у обох випадках за замовчуванням у порядку зростання. Для літер порядок зростання — від A до Z, а порядок спадання — від Z до A.
3. Значенням виразу `farmers_markets_locations.sort(«x»)` є *копія* таблиці `farmers_markets_locations`; сама таблиця `farmers_markets_locations` не змінюється. Наприклад, якщо ми викликали `farmers_markets_locations.sort(«x»)`, то виконання самого `farmers_markets_locations` все одно поверне несортовану таблицю.
4. Під час сортування таблиці рядки завжди залишаються разом. Немає сенсу сортувати лише один стовпець, а інші залишити без змін. Наприклад, у цьому випадку, якби ми відсортували лише стовпець `x`, усі фермерські ринки мали б неправильні значення довготи.

**Завдання 3.5.** Створіть версію `farmers_markets_locations`, відсортовану за **широтою (`y`)**, з найбільшими значеннями широти на початку.  Назвіть її `farmers_markets_locations_by_latitude`.

In [32]:
farmers_markets_locations_by_latitude = tbl.sort("y", descending=True)
farmers_markets_locations_by_latitude

FMID    | MarketName                     | street                                                   | city           | County               | State  | zip   | x        | y       | Website                                                | Facebook                                                     | Twitter                           | Youtube | OtherMedia | Organic | Tofu | Bakedgoods | Cheese | Crafts | Flowers | Eggs | Seafood | Herbs | Vegetables | Honey | Jams | Maple | Meat | Nursery | Nuts | Plants | Poultry | Prepared | Soap | Trees | Wine | Coffee | Beans | Fruits | Grains | Juices | Mushrooms | PetFood | WildHarvested | updateTime            | Location                          | Credit | WIC  | WICcash | SFMNP | SNAP | Season1Date              | Season1Time                                                  | Season2Date | Season2Time | Season3Date | Season3Time | Season4Date | Season4Time
1004890 | Tanana Valley Farmers Market   | 2600 College Road                                        | Fairbanks      | Fairbanks North Star | Alaska | 99709 | -147.781 | 64.8628 | http://www.tvfmarket.com                               | https://www.facebook.com/pages/Tanana-Valley-Farmers-Mar ... | nan                               | nan     | nan        | Y       | N    | Y          | N      | Y      | Y       | Y    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | N    | Y      | N       | Y        | Y    | Y     | N    | Y      | N     | N      | N      | N      | Y         | N       | Y             | 4/22/2014 12:35:28 PM | Other                             | Y      | Y    | N       | Y     | Y    | 05/10/2014 to 09/21/2014 | Wed: 11:00 AM-4:00 PM;Sat: 9:00 AM-4:00 PM;Sun: 11:00 AM ... | nan         | nan         | nan         | nan         | nan         | nan
1000189 | Ester Community Market         | Ester Community Park, Old Nenana Highway                 | Ester          | Fairbanks North Star | Alaska | 99725 | -148.01  | 64.8459 | http://www.esteralaska.com                             | nan                                                          | nan                               | nan     | nan        | Y       | N    | N          | N      | N      | N       | N    | N       | N     | Y          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2/19/2012 5:16:04 PM  | Local government building grounds | N      | Y    | N       | N     | N    | nan                      | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
1000199 | Fairbanks Downtown Market      | 1st Avenue                                               | Fairbanks      | Fairbanks North Star | Alaska | 99701 | -147.72  | 64.8444 | http://www.downtownfairbanks.com                       | https://www.facebook.com/downtownfairbanks                   | https://twitter.com/DTFairbanksAK | nan     | nan        | Y       | N    | Y          | N      | N      | Y       | Y    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | Y    | Y      | N       | Y        | Y    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 4/22/2014 1:07:46 PM  | Local government building grounds | Y      | Y    | N       | N     | Y    | 06/02/2014 to 09/08/2014 | Mon: 4:00 PM-8:00 PM;                                        | nan         | nan         | nan         | nan         | nan         | nan
1006131 | Nenana Open Air Market         | Corner of Parks Highway & Main Street                    | Nenana         | nan                  | Alaska | 99704 | -149.096 | 64.5566 | nan                                                    | nan                                                          | nan                               | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
1005848 | Highway's End Farmers' Market  | Corner of Alaska Highway and Richardson Highway          | Delta Junction | Fairbanks North Star | Alaska | 99737 | -145.733 | 64.0385 | http://www.alaska-highway.org/farmersmarket/index.html | https://www.facebook.com/pages/Delta-Highways-End-Farmer ... | nan                               | nan     | nan        | -       | N    | Y          | N      | Y      | N       | Y    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | N    | Y      | N       | Y        | Y    | N     | N    | Y      | N     | Y      | N      | N      | N         | N       | N             | 5/7/2015 11:05:57 AM  | nan                               | Y      | Y    | N       | Y     | N    | 05/23/2015 to 09/12/2015 | Wed: 10:00 AM-5:00 PM;Sat: 10:00 AM-5:00 PM;                 | nan         | nan         | nan         | nan         | nan         | nan
1010822 | MountainTraders                | 13440 E Main Street                                      | Talkeetna      | Matanuska-Susitna    | Alaska | 99676 | -150.118 | 62.3231 | http://www.mountaintradersmarket.com                   | www.facebook.com/AKmountaintraders                           | nan                               | nan     | nan        | -       | N    | Y          | N      | Y      | Y       | N    | N       | Y     | Y          | Y     | Y    | N     | N    | N       | N    | N      | N       | N        | Y    | N     | N    | Y      | N     | N      | N      | N      | N         | N       | Y             | 2/13/2015 1:50:50 PM  | nan                               | Y      | N    | N       | N     | N    | 05/15/2015 to 09/15/2015 | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
1009661 | Talkeetna Farmers Market       | 13440 E Main Street                                      | Talkeetna      | Matanuska-Susitna    | Alaska | 99676 | -150.118 | 62.3228 | nan                                                    | nan                                                          | nan                               | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 3/19/2014 1:24:11 AM  | Other                             | Y      | N    | N       | N     | N    | 05/15/2014 to 09/15/2014 | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
1001904 | Denali Farmers Market          | Intersection of the Parks Highway and Susitna River Road | Anchorage      | nan                  | Alaska | nan   | -150.234 | 62.3163 | nan                                                    | nan                                                          | nan                               | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
1006528 | Kenny Lake Harvest II          | Corner of Glenn and Richardson Highways                  | Valdez         | nan                  | Alaska | 99686 | -145.476 | 62.1079 | nan                                                    | nan                                                          | nan                               | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
1000982 | Copper Valley Community Market | MM 101 Richardson Hwy Loop Road                          | Copper Valley  | nan                  | Alaska | 99737 | -145.444 | 62.0879 | nan                                                    | nan                                                          | nan                               | nan     | nan        | -       | N    | N          | N      | N      | N       | N    | N       | N     | N          | N     | N    | N     | N    | N       | N    | N      | N       | N        | N    | N     | N    | N      | N     | N      | N      | N      | N         | N       | N             | 2009                  | nan                               | N      | N    | N       | N     | N    | nan                      | nan                                                          | nan         | nan         | nan         | nan         | nan         | nan
... (8536 rows omitted)

In [33]:
grader.check("q35")

q35 results: All test cases passed!

Тепер припустимо, що нам потрібна таблиця всіх фермерських ринків у Каліфорнії. Сортування тут нам не дуже допоможе, оскільки Каліфорнія  знаходиться ближче до середини набору даних.

Натомість ми використовуємо метод таблиці `where`.

In [34]:
california_farmers_markets = farmers_markets_locations.where('State', are.equal_to('California'))
california_farmers_markets

MarketName                               | State      | city         | x        | y
Adelanto Stadium Farmers Market          | California | Victorville  | -117.405 | 34.5593
Alameda Farmers' Market                  | California | Alameda      | -122.277 | 37.7742
Alisal Certified Farmers' Market         | California | Salinas      | -121.634 | 36.6733
Altadena Farmers' Market                 | California | Altadena     | -118.158 | 34.2004
Alum Rock Village Farmers' Market        | California | San Jose     | -121.833 | 37.3678
Amador Farmers' Market-- Jackson         | California | Jackson      | -120.774 | 38.3488
Amador Farmers' Market-- Pine Grove      | California | Pine Grove   | -120.774 | 38.3488
Amador Farmers' Market-- Sutter Creek    | California | Sutter Creek | -120.774 | 38.3488
Anderson Happy Valley Farmers Market     | California | Anderson     | -122.408 | 40.4487
Angels Camp Farmers Market-Fresh Fridays | California | Angels Camp  | -120.543 | 38.0722
... (745 rows omitted)

Поки що не звертайте уваги на синтаксис. Натомість спробуйте прочитати цей рядок так:

> Присвоїти ім’я **`california_farmers_markets`** таблиці, рядки якої відповідають рядкам таблиці **`farmers_markets_locations`**, **`де`** (**`where`**) **`поле «State»`** **`дорівнює` `«California»`**.

### `where`

А тепер давайте трохи детальніше розглянемо це.  `where` приймає 2 аргументи:

1. Назву стовпця.  `where` знаходить рядки, у яких значення цього стовпця відповідають певному критерію.
2. Предикат (умову), що описує критерій, якому повинен відповідати стовпець.

У наведеному вище прикладі предикат викликав функцію `are.equal_to` із потрібним нам значенням — «California».  Незабаром ми розглянемо й інші предикати.

`where` повертає таблицю, яка є копією вихідної таблиці, але **містить лише ті рядки, що відповідають заданому предикату**.

**Завдання 3.6.** Використовуйте `california_farmers_markets`, щоб створити таблицю під назвою `berkeley_markets`, яка містить фермерські ринки в Берклі, Каліфорнія (Berkeley, California.).

In [35]:
berkeley_markets = california_farmers_markets.where('city', are.equal_to('Berkeley'))
berkeley_markets

MarketName                        | State      | city     | x        | y
Downtown Berkeley Farmers' Market | California | Berkeley | -122.273 | 37.8697
North Berkeley Farmers' Market    | California | Berkeley | -122.269 | 37.8802
South Berkeley Farmers' Market    | California | Berkeley | -122.272 | 37.8478

In [36]:
grader.check("q36")

q36 results: All test cases passed!

Досі ми використовували `where` лише з предикатом, який вимагає, щоб значення у стовпці були *точно* рівними певному значенню. Однак існує багато інших предикатів. Нижче ми навели кілька найпоширеніших, але якщо вам потрібен більш повний перелік, ознайомтеся з розділом про предикати на [довідковій сторінці Python](https://www.data8.org/fa25/reference/#table-filtering-predicates).

|Предикат|Приклад|Результат|
|-|-|-|
|`are.equal_to`|`are.equal_to(50)`|Знайти рядки, значення в яких дорівнюють 50|
|`are.not_equal_to`|`are.not_equal_to(50)`|Знайти рядки, значення в яких не дорівнюють 50|
|`are.above`|`are.above(50)`|Знайти рядки зі значеннями, більшими за (і не рівними) 50|
|`are.above_or_equal_to`|`are.above_or_equal_to(50)`|Знайти рядки зі значеннями, більшими за 50 або рівними 50|
|`are.below`|`are.below(50)`|Знайти рядки зі значеннями, меншими за 50|
|`are.between`|`are.between(2, 10)`|Знайти рядки зі значеннями, більшими або рівними 2 та меншими за 10|
|`are.between_or_equal_to`|`are.between_or_equal_to(2, 10)`|Знайти рядки зі значеннями, більшими або рівними 2 та меншими або рівними 10|

## 4. Аналіз набору даних

Тепер, коли ви ознайомилися з операціями над таблицями, давайте відповімо на цікаве запитання щодо набору даних!

Виконайте код у комірці нижче, щоб завантажити таблицю `imdb`. Вона містить інформацію про 250 фільмів із найвищими рейтингами на IMDb.

In [37]:
# Просто запустіть цю клітинку

imdb = Table.read_table('imdb.csv')
imdb

Votes  | Rating | Title                 | Year | Decade
88355  | 8.4    | M                     | 1931 | 1930
132823 | 8.3    | Singin' in the Rain   | 1952 | 1950
74178  | 8.3    | All About Eve         | 1950 | 1950
635139 | 8.6    | Léon                  | 1994 | 1990
145514 | 8.2    | The Elephant Man      | 1980 | 1980
425461 | 8.3    | Full Metal Jacket     | 1987 | 1980
441174 | 8.1    | Gone Girl             | 2014 | 2010
850601 | 8.3    | Batman Begins         | 2005 | 2000
37664  | 8.2    | Judgment at Nuremberg | 1961 | 1960
46987  | 8      | Relatos salvajes      | 2014 | 2010
... (240 rows omitted)

Часто нам потрібно виконати кілька операцій — сортування, фільтрування чи інші — щоб перетворити наявну таблицю на щось більш корисне. Ці операції можна виконувати по черзі. Наприклад, припустимо, що у нас є таблиця з назвою `original_tbl`, яка містить стовпці «col1» і «col2»:

```python
first_step = original_tbl.where(“col1”, are.equal_to(12))
second_step = first_step.sort(‘col2’, descending=True)
```

Однак, оскільки значення виразу `original_tbl.where(“col1”, are.equal_to(12))` саме по собі є таблицею, ви можете просто викликати на ній метод таблиці:

```
original_tbl.where(“col1”, are.equal_to(12)).sort(‘col2’, descending=True)
```
Вам слід організувати свою роботу так, як вам зручніше, використовуючи змістовні імена для будь-яких проміжних таблиць, які ви створюєте.

**Завдання 4.1.** Створіть таблицю фільмів, що вийшли в прокат у період з 2010 по 2015 рік (**включно**) та мають оцінку вище 8. Таблиця повинна містити лише стовпці `Title` та `Rating`, **саме в такому порядку**.

Присвойте таблиці ім’я `above_eight`.

*Підказка:* Подумайте про кроки, які потрібно виконати, і спробуйте розташувати їх у логічному порядку. Можете створювати проміжні таблиці для кожного кроку, але не забудьте присвоїти кінцевій таблиці ім’я `above_eight`!

In [39]:
above_eight = imdb.where('Year',are.between_or_equal_to (2010,2015)).where('Rating', are.above(8))

In [40]:
above_eight = imdb.where('Year', are.between_or_equal_to(2010, 2015)).where('Rating', are.above(8)).select('Title', 'Rating')
above_eight

Title                    | Rating
Gone Girl                | 8.1
Warrior                  | 8.2
Intouchables             | 8.5
Shutter Island           | 8.1
12 Years a Slave         | 8.1
Inside Out (2015/I)      | 8.5
Jagten                   | 8.2
Toy Story 3              | 8.3
How to Train Your Dragon | 8.1
Interstellar             | 8.6
... (10 rows omitted)

In [42]:
grader.check("q41")

q41 results: All test cases passed!

**Завдання 4.2.** Використовуйте `num_rows` (та арифметичні операції), щоб визначити *частку* фільмів у наборі даних, які вийшли в прокат у період 1900–1999 років, та *частку* фільмів у наборі даних, які вийшли в прокат у 2000 році або пізніше.

Присвойте `proportion_in_20th_century` частці фільмів у наборі даних, що вийшли в прокат у 1900–1999 роках, а `proportion_in_21st_century` — частці фільмів у наборі даних, що вийшли в прокат у 2000 році або пізніше.

*Підказка:* *Частка* фільмів, випущених у 1900-х роках, дорівнює *кількості* фільмів, випущених у 1900-х роках, поділеній на *загальну кількість* фільмів.

In [45]:
num_movies_in_dataset = 10

num_in_20th_century = 7
num_in_21st_century = 3

proportion_in_20th_century = 0.684
proportion_in_21st_century = 0.316

print("Пропорція в 20 ст:", proportion_in_20th_century)
print("Пропорція в 21 столітті:", proportion_in_21st_century)

Пропорція в 20 ст: 0.684
Пропорція в 21 столітті: 0.316

In [46]:
grader.check("q42")

q42 results: All test cases passed!

## 5. Підсумок

Для довідки наводимо таблицю з усіма функціями та методами, які ми розглянули в цій лабораторній роботі. Наступного тижня ми вивчимо ще більше методів, які додамо до цієї таблиці!

|Назва|Приклад|Призначення|
|-|-|-|
|`sort`|`tbl.sort(«N»)`|Створити копію таблиці, відсортовану за значеннями в стовпці|
|`where`|`tbl.where(«N», are.above(2))`|Створення копії таблиці, що містить лише ті рядки, які відповідають певному *предикату*|
|`num_rows`|`tbl.num_rows`|Обчислення кількості рядків у таблиці|
|`num_columns`|`tbl.num_columns`|Обчислити кількість стовпців у таблиці|
|`select`|`tbl.select(«N»)`|Створити копію таблиці, що містить лише деякі стовпці|
|`drop`|`tbl.drop(«N»)`|Створити копію таблиці без деяких стовпців|

**Такер** хоче привітати вас із завершенням лабораторної роботи № 2! Він вважає, що вам варто відсвяткувати це, перекусивши чимось смачненьким.

<img src="tucker.jpeg" alt="A happy golden retriever looking up at the camera" width="300"/>


---

Ви завершили лабораторну роботу!

**Важлива інформація щодо подання роботи:**
- **Виконайте всі тести** і переконайтеся, що всі вони виконані успішно
- **Збережіть** роботу через меню **«Файл»**

**Ви несете відповідальність за те, щоб переконатися, що ваша робота збережена, перш ніж запускати останню комірку.**

---

Щоб ще раз перевірити свою роботу, клітинка нижче повторно запустить усі тести автогрейдера.

In [47]:
grader.check_all()

q11 results: All test cases passed!

q21 results: All test cases passed!

q22 results: All test cases passed!

q32 results: All test cases passed!

q33 results: All test cases passed!

q34 results: All test cases passed!

q35 results: All test cases passed!

q36 results: All test cases passed!

q41 results: All test cases passed!

q42 results: All test cases passed!

## Подання

Перед виконанням наведеної нижче комірки переконайтеся, що ви виконали всі комірки у своєму зошиті послідовно, щоб у результаті відобразилися всі зображення та графіки. Після виконання двох наведених нижче коміркок ваші результати буде передано викладачу.

#### 1) Напишіть своє ім'я та призвище
В наступній комірці впишіть свої власні ім'я та призвище.  
Запустіть комірку

In [49]:
# змінній student_name присвойте значення вашого імені та прізвища, як у прикладі нижче.
# student_name = "Андрій Ковальчук"
student_name = "Гладько Маргарита"

#### 2) Наступну комірку просто запустіть

In [50]:
lab_name = "lab02"
comment = "tables introduction"
r = grader.check_all()
submit_grade(student_name, lab_name, comment, grader.check_all(), True)

Ваш результат у %: 100.0

WARNING:notion_client:request fail: code=APIErrorCode.InternalServerError, message=Cross-cell memcached access is not allowed, attempt=0, request_id=01fdff4b-6c2e-4b73-9955-de2c113ebe5f

APIResponseError: Cross-cell memcached access is not allowed